version: "2"
run:
  timeout: 5m
linters:
  default: all
  enable:
    - exhaustruct_v5
    - gomodguard_v2
    - wsl_v5
  disable:
    - godot
    - varnamelen
    - wrapcheck
    - exhaustruct
    - gomodguard
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - radic
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
